### ISSUE TITLE
Extend the QC relaxation

### ISSUE THREAD

**Issue by mrnarimani** [lanl-ansi/PowerModelsAnnex.jl#26]
I want to run the OBBT code for a QC relaxation in PowerModelsAnnex.  I set the model_constructor in OBBT code to “QCWRTriNoLinkPowerModel” and run the following command but got an error.
```
run_obbt_opf(case,IpoptSolver())
```
ERROR: UndefVarError: QCWRTriNoLinkPowerModel not defined
Can you please let me know how I can run the OBBT code for a model_constructor in PowerModelAnnex. 
I also want to add several new constraints to the code. Where is the best location to add the constraints? Should I add them to the model_constructor or post_qc_opf  in opf.jl script? I will appreciate any help. Thanks in advance!

**Comment by kaarthiksundar** [comment]
The following code works for me: 

````julia
using PowerModels
using PowerModelsAnnex
using Ipopt

solver_args = Dict{Symbol,Any}()
solver_args[:tol] = 1e-6
solver_args[:print_level] = 0
solver = IpoptSolver(; solver_args...)
run_obbt_opf("$(Pkg.dir("PowerModels"))/test/data/matpower/case5_asym.m", solver, max_iter=1, model_constructor=QCWRTriNoLinkPowerModel)
````

**Comment by kaarthiksundar** [comment]
As for adding several new constraints - I would recommend to create a new model_constructor like the ``QCWRTriNoLinkPowerModel`` in PowerModelsAnnex and add or modify the constraints. If you have your code in your fork, you could point me to the code and I can help with completing it.

**Comment by mrnarimani** [comment]
Thanks for the response. Actually I extended the OBBT code to tighten the voltage magnitude difference as well. I have modified the QCWRTriPowerModel type in order to define new constraint for voltage magnitude difference (i.e., vd). Adding these modifications could tighten the QC relaxation for most cases (i.e., I got a higher lower bound for most cases compare to the those obtained by primary OBBT code). However, I want to add other new constraints but I cannot to call those constraints because I encounter with errors (e.g., No method match to the constraint etc.). Following are two of those constraints that I want to add to the code. I am wondering if you can help me to call them in the code. 
```
 function constraint_voltage_magnitude_diff_sqr_inequality(pm::GenericPowerModel{QCWRTriForm}, n::Int, c::Int, f_bus, t_bus)
     w_fr = var(pm, n, c, :w, f_bus)
     w_to = var(pm, n, c, :w, t_bus)
     vv = var(pm, n, c, :vv, (f_bus, t_bus))
     vd = var(pm, n, c, :vd, (f_bus, t_bus))

     @constraint(pm.model, vd_squared <= w_fr - 2*vv + w_to)
            println("constraint3")
 end

 function constraint_voltage_magnitude_diff_link(pm::GenericPowerModel{QCWRTriForm}, n::Int, c::Int, f_bus, t_bus, g, b, b_fr)
     p_fr = var(pm, n, c, :p, f_idx)
     q_fr = var(pm, n, c, :q, f_idx)
     q_to = var(pm, n, c, :q, t_idx)
     p_to = var(pm, n, c, :p, t_idx)
     vd = var(pm, n, c, :vd, (f_bus, t_bus))
     vvv_fr = var(pm, n, c, :vvv_fr, f_bus)
  vvv_to = var(pm, n, c, :vvv_to, t_bus)

  @constraint(pm.model,  vvv_fr + vvv_to == (1/(g^2+b^2+b*b_fr))*(g*(p_fr-p_to)-b*(q_fr-q_to)))
         println("constraint4")
 end
```
I have done all the modifications in PowerModels and it would be great to finish this project in PowerModels. 
I will map all modifications to PowerModelAnnex if push comes to shove. Thus, I will appreciate any hint to call these constraints in my code. Note that I have implemented all the new constraints but I cannot call them except the following one.

```
    @constraint(pm.model, v[i] - v[j] == vd[bp])
```

**Comment by kaarthiksundar** [comment]
The issue is difficult to debug without the code - do you have the code in some repo so that it can be downloaded and the error be reproduced?

**Comment by mrnarimani** [comment]
Thanks for the kind response. I have changed obbt.jl and wr.jl which you can find them through the following address. I also put a test systems that you need to run the code (several columns have been added mpc.branch through thr mpc.branch_limit matrix)
https://github.com/mrnarimani/Extension-of-OBBT-
 The code doesn’t produce any error. The problem is I cannot call the following constraints

constraint_voltage_magnitude_diff_dim3 (line 957 wr.jl)
constraint_voltage_magnitude_diff_dim2 (line 944 wr.jl)
constraint_voltage_magnitude_diff_dim1 (line 957 wr.jl)
constraint_voltage_magnitude_diff_link (line 916 wr.jl)
constraint_voltage_magnitude_difference_neghboring_buses (line 833 wr.jl)

I will appreciate it if you help me to call these constraints.

**Comment by kaarthiksundar** [comment]
I would advise to create a new model may be by the name QCWRTriVPowerModel and QCWRTriVForm that is a child of the type QCWRTriPowerModel and QCWRTriForm, respectively. 

Overload the variable_voltage and constraint_voltage functions with your modifications. 

Then, it should work. As an example, check the QCWRTriNoLinkPowerModel and QCWRTriNoLinkForm in PowerModelsAnnex's wr.jl file. 

Fork PowerModelsAnnex and make the modifications in your fork.

**Comment by mrnarimani** [comment]
Thanks for the response! Can I use the OBBT code with post_qc_opf model in PowerModelsAnnex? I do know that it is possible to run OPF with this model as in the postscript. I am wondering if I would be able to do run the OBBT code with post_qc_opf? If it is possible please let me know how I can do that. Thanks in advance!
P.S.
```
using PowerModelsAnnex
using PowerModels
using JuMP
using Ipopt

ipopt = IpoptSolver()
model = Model(solver=ipopt)

data = PowerModels.parse_file("case3.m")
post_ac_opf(data, model)
status = solve(model)
```

**Comment by kaarthiksundar** [comment]
Yes, you can do that without any issues. But since your OBBT is doing BT on more variables, just add the OBBT function under a different name to PowerModelsAnnex.jl and use that.

**Comment by mrnarimani** [comment]
Thanks for the response! I checked the QCWRTriNoLinkPowerModel and QCWRTriNoLinkForm in PowerModelsAnnex but there was no 'variable_voltage" function in the model. Can I add the function to the model and modified that with new variables? 
There was a PMs in front of functions' name. Can you please explain what is that for? Thanks in advance! The post_qc_opf model worked after adding the modifications. I am about to map the modifications into QCWRTriXPowerModel as you suggested.

**Comment by kaarthiksundar** [comment]
Yes, just add the function. 

PMs is a short hand for PowerModels

Check line 11 in src/PowerModelsAnnex.jl

You do that if you want to invoke already implemented PowerModels functions.

**Comment by mrnarimani** [comment]
I have modified a new type in PowerModelsAnnex named "QCWRTriVPowerModel".  I have added new variables and constraints to the PowerModelsAnnex. There is one issue with recognizing buspairs just before adding new variables. Can you please guide me how I can pass buspairs information into the variable_voltage function.  Following is the type that I have defined. Thanks in advance!



```
export QCWRTriVPowerModel, QCWRTriVForm

@compat abstract type QCWRTriVForm <: PMs.QCWRTriForm end

const QCWRTriVPowerModel = PMs.GenericPowerModel{QCWRTriVForm}

"default QC trilinear without linking constraint model constructor"
QCWRTriVPowerModel(data::Dict{String,Any}; kwargs...) = PMs.GenericPowerModel(data, QCWRTriVForm; kwargs...)


function PMs.variable_voltage(pm::GenericPowerModel{T}; kwargs...) where T <: QCWRTriVForm


    PMs.variable_voltage_angle(pm; kwargs...)
    PMs.variable_voltage_magnitude(pm; kwargs...)

    PMs.variable_voltage_magnitude_sqr(pm; kwargs...)
    PMs.variable_voltage_product(pm; kwargs...)

    PMs.variable_voltage_angle_difference(pm; kwargs...)
    PMs.variable_voltage_magnitude_product(pm; kwargs...)
    PMs.variable_cosine(pm; kwargs...)
    PMs.variable_sine(pm; kwargs...)
    PMs.variable_current_magnitude_sqr(pm; kwargs...)


    ## I have added following variables to take care of voltage magnitude difference constraints
    ref = PMs.build_ref(data)[:nw][0]
    buspair = ref[:buspairs][bp]

    lower_vd = buspairs["vdiff_min"]
    upper_vd = buspairs["vdiff_max"]
    @variable(model, lower_vd <= vd[bp in keys(ref[:buspairs])] <= upper_vd)

    lower_vvv_fr = min(buspairs[bp]["vm_fr_min"]*buspairs[bp]["vdiff_min"], buspairs[bp]["vm_fr_max"]*buspairs[bp]["vdiff_min"])
    upper_vvv_fr = max(buspairs[bp]["vm_fr_max"]*buspairs[bp]["vdiff_max"], buspairs[bp]["vm_fr_min"]*buspairs[bp]["vdiff_max"])
    @variable(model, lower_vvv_fr[bp] <= vvv_fr[bp in keys(ref[:buspairs])] <= upper_vvv_fr[bp])



    lower_vvv_to = min(buspairs[bp]["vm_to_min"]*buspairs[bp]["vdiff_min"], buspairs[bp]["vm_to_max"]*buspairs[bp]["vdiff_min"])
    upper_vvv_to = max(buspairs[bp]["vm_to_max"]*buspairs[bp]["vdiff_max"], buspairs[bp]["vm_to_min"]*buspairs[bp]["vdiff_max"])
    @variable(model, lower_vvv_fr[bp] <= vvv_to[bp in keys(ref[:buspairs])] <= upper_vvv_fr[bp])


    lower_w_squared = (buspairs[bp]["vm_fr_min"])^2*(buspairs[bp]["vm_to_min"])^2
    upper_w_squared = (buspairs[bp]["vm_fr_max"])^2*(buspairs[bp]["vm_to_max"])^2
    @variable(model, lower_w_squared[bp] <= w_squared[bp in keys(ref[:buspairs])] <= upper_w_squared[bp])


    lower_vd_squared = 0
    upper_vd_squared = max((buspairs[bp]["vdiff_min"][cnd])^2,(buspairs[bp]["vdiff_max"][cnd])^2)
    @variable(model, lower_w_squared[bp] <= vd_squared[bp in keys(ref[:buspairs])] <= upper_vd_squared[bp])


    lower_vv = buspairs[bp]["vm_fr_min"]*buspairs[bp]["vm_to_min"]
    upper_vv = buspairs[bp]["vm_fr_max"]*buspairs[bp]["vm_to_max"]
    @variable(model, lower_vv[bp] <= vv[bp in keys(ref[:buspairs])] <= upper_vv[bp])

    #### End of adding variables

end

function PMs.constraint_voltage(pm::GenericPowerModel{T}, n::Int, c::Int) where T <: QCWRTriVForm
    v = var(pm, n, c, :vm)
    t = var(pm, n, c, :va)

    td = var(pm, n, c, :td)
    si = var(pm, n, c, :si)
    cs = var(pm, n, c, :cs)

    w = var(pm, n, c, :w)
    wr = var(pm, n, c, :wr)
    lambda_wr = var(pm, n, c, :lambda_wr)
    wi = var(pm, n, c, :wi)
    lambda_wi = var(pm, n, c, :lambda_wi)

    for (i,b) in ref(pm, n, :bus)
        InfrastructureModels.relaxation_sqr(pm.model, v[i], w[i])
    end

    for bp in ids(pm, n, :buspairs)
        i,j = bp
        @constraint(pm.model, t[i] - t[j] == td[bp])

        PMs.relaxation_sin(pm.model, td[bp], si[bp])
        PMs.relaxation_cos(pm.model, td[bp], cs[bp])
        InfrastructureModels.relaxation_trilinear(pm.model, v[i], v[j], cs[bp], wr[bp], lambda_wr[bp,:])
        InfrastructureModels.relaxation_trilinear(pm.model, v[i], v[j], si[bp], wi[bp], lambda_wi[bp,:])

        # this constraint is redudant and useful for debugging
        #InfrastructureModels.relaxation_complex_product(pm.model, w[i], w[j], wr[bp], wi[bp])
    end

    for (i,branch) in ref(pm, n, :branch)
        pair = (branch["f_bus"], branch["t_bus"])
        buspair = ref(pm, n, :buspairs, pair)
        bp = (branch["f_bus"], branch["t_bus"])
        buspair = ref[:buspairs][bp]
        tm = branch["tap"]


        # to prevent this constraint from being posted on multiple parallel branchs
        if buspair["branch"] == i
            g, b = PowerModels.calc_branch_y(branch)
            tr, ti = PowerModels.calc_branch_t(branch)
            g_fr = branch["g_fr"]
            b_fr = branch["b_fr"]


            # extract variables
            p_fr = p[(i,branch["f_bus"],branch["t_bus"])]
            q_fr = q[(i,branch["f_bus"],branch["t_bus"])]
            w_fr = w[branch["f_bus"]]
            w_to = w[branch["t_bus"]]
            @constraint(model,  vvv_fr[bp] + vvv_to[bp] == (1/(g^2+b^2+b*b_fr))*(g*(p_fr-p_to)-b*(q_fr-q_to)))

            PMs.constraint_power_magnitude_sqr(pm, i, nw=n, cnd=c)
            PMs.constraint_power_magnitude_link(pm, i, nw=n, cnd=c)
        end
    end


    for (bp, buspair) in ref[:buspairs]
        i,j = bp
        @constraint(model, vm[i] - vm[j] == vd[bp])


        ub_vdiff = buspair["vdiff_max"]
        ul_vdiff = buspair["vdiff_min"]
        @constraint(model, vm[i] - vm[j] <= ub_vdiff)
        @constraint(model, vm[i] - vm[j] >= lb_vdiff)


        alpha_fr = buspair["alpha_fr"]
        beta_fr = buspair["beta_fr"]

        @constraint(pm.model, v[j] - alpha_fr*v[i] <= beta_fr)
        @constraint(pm.model, v[j] - alpha_fr*v[i] >= -beta_fr)

        @constraint(pm.model,   w[j] - 2*alpha_fr*vv[bp] + alpha_fr^2 *w[i] <= beta_fr^2)

        @constraint(pm.model,  w[j] + 2*alpha_fr*vv[bp] + alpha_fr^2 * w[i] <= 4*alpha_fr*vv[bp] + beta_fr^2)


        @constraint(model, vv[bp] == (w[i] + w[j] - vd_squared[bp])/2)
        @constraint(model, vd_squared[bp] <= w[i] - 2*vv[bp] + w[j])
    end

end
```

**Comment by kaarthiksundar** [comment]
@mrnarimani you are confusing things. Give me some time. I will get you an implementation over the weekend in a branch within PowerModelsAnnex.jl with an example.

**Comment by mrnarimani** [comment]
Thank you so much! I am looking forward to seeing your comments.

**Comment by kaarthiksundar** [comment]
You seem to have deleted some of the comments. I was under the impression you figured it out.

**Comment by mrnarimani** [comment]
Sorry for the inconvenience! I have deleted those comments after sharing
the code by pulling a request. I have not figure the issue out. I have
shared three different scripts the first one is modified wr.jl in
POwerModelsAnnex, the second one is opf.ji in PowerModelsAnnex, and the
third one is the modified OBBT.jl in PowerModels. I will appreciate it if
you let me know about my possible mistakes in these codes especially the
first and the third ones.  Thanks in advance!
