### ISSUE TITLE
Run the OBBT.jl by post_qc_opf model as a model_constructor

### ISSUE THREAD

**Issue by mrnarimani** [lanl-ansi/PowerModelsAnnex.jl#27]
Is it possible to runt the OBBT code with post_qc_opf model in PowerModelsAnnex as a model constructor? Please let me know how I can do that if it is possible. Thanks in advance!

**Comment by kaarthiksundar** [comment]
Nope, you have to use a model constructor like QCWRTriPowerModel

**Comment by mrnarimani** [comment]
Thanks! How about the objective function value. How can I extract it from the solution?
