### ISSUE TITLE
FrontEnd Segmentation Fault in Julia v0.7

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsAnnex.jl#29]
@eperim, I am working on migrating this code to work on v0.6/v0.7/v1.0.  Currently I am stuck with a segmentation fault that occurs during compilation on Julia v0.7 while in `frontend/units.jl`.  The issue seems to be in this call, `Unitful.register(current_module())`.

Can you have a look and see if you can suggest a fix?

Full trace,
```
using PowerModelsAnnex
...
┌ Warning: `current_module()` is deprecated, use `@__MODULE__` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
WARNING: eval from module Unitful to PowerModelsAnnex:    
Expr(:call, :/, Unitful.FreeUnits{(Unitful.Unit{:WattHour, Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=2, den=1)), Unitful.Dimension{:Mass}(power=Base.Rational{Int64}(num=1, den=1)), Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=-2, den=1)))}}(tens=6, power=Base.Rational{Int64}(num=1, den=1)),), Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=2, den=1)), Unitful.Dimension{:Mass}(power=Base.Rational{Int64}(num=1, den=1)), Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=-2, den=1)))}}(), Unitful.FreeUnits{(Unitful.Unit{:Minute, Unitful.Dimensions{(Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=1, den=1)),)}}(tens=0, power=Base.Rational{Int64}(num=1, den=1)),), Unitful.Dimensions{(Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=1, den=1)),)}}())
  ** incremental compilation may be broken for this module **

WARNING: eval from module Unitful to PowerModelsAnnex:    
Expr(:call, :*, Unitful.FreeUnits{(Unitful.Unit{:Watt, Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=2, den=1)), Unitful.Dimension{:Mass}(power=Base.Rational{Int64}(num=1, den=1)), Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=-3, den=1)))}}(tens=6, power=Base.Rational{Int64}(num=1, den=1)),), Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=2, den=1)), Unitful.Dimension{:Mass}(power=Base.Rational{Int64}(num=1, den=1)), Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=-3, den=1)))}}(), Unitful.FreeUnits{(Unitful.Unit{:Hour, Unitful.Dimensions{(Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=1, den=1)),)}}(tens=0, power=Base.Rational{Int64}(num=1, den=1)),), Unitful.Dimensions{(Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=1, den=1)),)}}())
  ** incremental compilation may be broken for this module **


signal (11): Segmentation fault: 11
in expression starting at no file:0
jl_gc_pool_alloc at /Users/osx/buildbot/slave/package_osx64/build/src/gc.c:963
jl_gc_alloc at /Users/osx/buildbot/slave/package_osx64/build/src/./julia_internal.h:274
_new_array_ at /Users/osx/buildbot/slave/package_osx64/build/src/array.c:99
...
```

**Comment by eperim** [comment]
@ccoffrin This seems like a strange error. I had first tested `Unitful`, then `PowerModelsAnnex` precompiled alright (with all those warnings). However, if (and only if) I try to do `using PowerModelsAnnex` without doing `using Unitful` first, I get a segmentation fault. Could you test if you can reproduce this?

**Comment by ccoffrin** [comment]
Agreed that it is strange.

On `master` I tried clearing my compiled cache and then ran `using Unitful; using PowerModelsAnnex` which yielded similar segfault results.  I have noticed that compilation will work randomly about 10% of the times I do using or test.

**Comment by eperim** [comment]
Here `using Unitful; using PowerModelsAnnex` seems to work 100% of the time. However, the tests always throw the segfault. I will try to see if someone who knows more julia than I do can help over here.

**Comment by ccoffrin** [comment]
Any updates on this?  Would you mind if I drop the tests for the frontend for now so that the package can be working in Julia v0.7/v1.0?

**Comment by eperim** [comment]
Tried a couple of things, but nothing conclusive yet. I don't mind at all if you turn off the tests (or the module altogether, if necessary). As soon as we have a solution I'll push it.

**Comment by ccoffrin** [comment]
It seems that we can produce your experience on travis, https://travis-ci.org/lanl-ansi/PowerModelsAnnex.jl/builds/454089255.  Going to merge and tag with the frontend tests commented out.

**Comment by ccoffrin** [comment]
In the end, it seems that in some rare cases the segfault was reproducible on travis, https://travis-ci.org/lanl-ansi/PowerModelsAnnex.jl/jobs/454117634.

**Comment by nicoleepp** [comment]
This is fixed locally for me with https://github.com/lanl-ansi/PowerModelsAnnex.jl/pull/32
