### ISSUE TITLE
network2pmc should create an key-empty value pair "shunt" => Dict{String,Any}() if there is no shunt.

### ISSUE THREAD

**Issue by mjamei19** [lanl-ansi/PowerModelsAnnex.jl#35]
Right now, passing a network of type `::Network` into network2pmc function would create a PowerModels dictionary that does not have the key `shunt` if there is no shunt element in the original network. However, PowerModels.jl checks for that key every time it wants to run a form of powerflow/optimal power flow and fails as it couldn't find the key. If there is no shunt element, network2pmc should still create a key-empty value pair "shunt" => Dict{String,Any}().

**Comment by ccoffrin** [comment]
CC @eperim @nicoleepp 

You might also want to add a similar empty list for storage devices.  See https://github.com/lanl-ansi/PowerModels.jl/pull/404

**Comment by ccoffrin** [comment]
@mjamei19, close this issue if this is working for you now.
