### ISSUE TITLE
Inconsistent behavior of `build_pmc!`

### ISSUE THREAD

**Issue by lsindoni** [lanl-ansi/PowerModelsAnnex.jl#37]
The frontend unit provides a `build_pmc!` functionality that converts the data contained in the dataframes into the dictionary that then PowerModels can handle to construct the model for the optimization. There seems to be some instability in the conversions between dataframes and dictionary that lead to incorrect behavior.
Here is an attempt at a minimal presentation of the problem:

```julia
# - initial definitions and imports
using PowerModels, PowerModelsAnnex, Ipopt, Missings
PM = PowerModels; PMA = PowerModelsAnnex;
solver = IpoptSolver(print_level=0)

# Load a grid, extract the data used for constructing the PowerModel
net = PMA.Network("<your path to the case>/case5.m")
original = PMA.pmc(net)

# Run the opf, successfully
opf1 = PM.run_dc_opf(original, solver)

# Now, rebuild the pmc inside the net
net2 = deepcopy(net)
PMA.build_pmc!(net2)
rebuilt = PMA.pmc(net2)
opf2 = PM.run_dc_opf(rebuilt, solver)
```

While the first opf works, the second fails:
```
julia> opf2 = PM.run_dc_opf(rebuilt, solver)
ERROR: Only cost models of types 1 and 2 are supported at this time, given cost model type of nothing
Stacktrace:
 [1] objective_min_fuel_cost(::PowerModels.GenericPowerModel{PowerModels.DCPlosslessForm}) at /path/to/packages/packages/v0.6/PowerModels/src/core/objective.jl:57
 [2] post_opf(::PowerModels.GenericPowerModel{PowerModels.DCPlosslessForm}) at /path/to/packages/packages/v0.6/PowerModels/src/prob/opf.jl:25
 [3] #build_generic_model#149(::Bool, ::Bool, ::Array{Any,1}, ::Function, ::Dict{String,Any}, ::Type{T} where T, ::PowerModels.#post_opf) at /path/to/packages/packages/v0.6/PowerModels/src/core/base.jl:241
 [4] #run_generic_model#147(::Function, ::Array{Any,1}, ::Function, ::Dict{String,Any}, ::Type{T} where T, ::Ipopt.IpoptSolver, ::Function) at /path/to/packages/packages/v0.6/PowerModels/src/core/base.jl:211
 [5] #run_opf#583 at /path/to/packages/packages/v0.6/PowerModels/src/prob/opf.jl:15 [inlined]
 [6] run_opf(::Dict{String,Any}, ::Type{T} where T, ::Ipopt.IpoptSolver) at /path/to/packages/packages/v0.6/PowerModels/src/prob/opf.jl:15
 [7] #run_dc_opf#582 at /path/to/packages/packages/v0.6/PowerModels/src/prob/opf.jl:10 [inlined]
 [8] run_dc_opf(::Dict{String,Any}, ::Ipopt.IpoptSolver) at /path/to/packages/packages/v0.6/PowerModels/src/prob/opf.jl:10
```

Inspecting the dictionaries that are created, `original` and `rebuilt` there seem to be a number of differences. Among the others, the ones that trigger this particular error are:
```
julia> # Among the differences:
       println("Original number of cost coefficients (bus 4): ", original["gen"]["4"]["ncost"])
Original number of cost coefficients (bus 4): 3

julia> println("New number of cost coefficients (bus 4): ", rebuilt["gen"]["4"]["ncost"])
New number of cost coefficients (bus 4): 0

julia> println("Original cost type (bus 1):", original["gen"]["1"]["model"])
Original cost type (bus 1):2

julia> println("New cost type (bus1):", rebuilt["gen"]["1"]["model"])
New cost type (bus1):-1
```
(The generators are chosen for illustrative purposes, I get these problems for all of them)

There are also other differences, that impact the construction of the OPF model (in particular, assumptions about the keys of some dictionaries being strings vs integers), but in general it seems that we need to make this `build_pmc!` function (and the construction of the `Network`) a little bit more consistent.

Setup (which I don't think is important for this particular problem): julia 0.6.4
```
julia> Pkg.status("PowerModels")
 - PowerModels                   0.8.8

julia> Pkg.status("PowerModelsAnnex")
 - PowerModelsAnnex              0.1.7+             master
```

**Comment by lsindoni** [comment]
Digging inside the various functions, I've found a potential origin for the problem with the generator cost functions. I believe that [here](https://github.com/lanl-ansi/PowerModelsAnnex.jl/blob/c1ac9bd207bbd26120dcd759c1b0e7f7a1f28a73/src/frontend/frontend.jl#L1100) the arguments of the first `in` should be reversed.

**Comment by ccoffrin** [comment]
CC @eperim

**Comment by lsindoni** [comment]
I think that I have a fix, tests passing and behavior above fixed. I'll open a PR now. I'd like to add more tests later.

**Comment by eperim** [comment]
> I believe that here the arguments of the first in should be reversed

Very true, sorry for the oversight.

**Comment by ccoffrin** [comment]
Is this closed by #38?

**Comment by nicoleepp** [comment]
Yes, also, can the fix be tagged in master? Thank you

**Comment by ccoffrin** [comment]
done and done.
