### ISSUE TITLE
Missing generator cost data for objective function?

### ISSUE THREAD

**Issue by lroald** [lanl-ansi/PowerModelsAnnex.jl#44]
The objective functions in PowerModelsAnnex loop over the generators and their cost coefficients. However, when there is a generator with zero cost coefficients, it seems like this data is taken out of the reference and the code throws an error at the objective function. 

Example:
If generator 3 has zero cost coefficients, ref[:gen][3]["cost"] = [] 
In this case, the code throws an out-of-bounds error because the objective tries to access
ref[:gen][3]["cost"][1], ref[:gen][3]["cost"][2] and ref[:gen][3]["cost"][3]

@objective(model, Min,
    sum(gen["cost"][1]*pg[i]^2 + gen["cost"][2]*pg[i] + gen["cost"][3] for (i,gen) in ref[:gen]) +
    sum(dcline["cost"][1]*p_dc[from_idx[i]]^2 + dcline["cost"][2]*p_dc[from_idx[i]] + dcline["cost"][3] for (i,dcline) in ref[:dcline])
)

I assume this is due to some update in the way the reference is constructed, and maybe already fixed in PowerModels? Is there a good place to see an example for how to write the objective in this case?

**Comment by ccoffrin** [comment]
This is related to a recent PowerModels update that now supports more flexible cost functions.  Can you double check your local code includes this section,
```
PowerModels.standardize_cost_terms(data, order=2)
```
https://github.com/lanl-ansi/PowerModelsAnnex.jl/blob/master/src/model/ac-opf.jl#L48

`standardize_cost_terms` with order 2 should restore the previous semantics.

If there is still an issue, if you can send an example data file I'll fix it.
