### ISSUE TITLE
Security Constrained DC OPF

### ISSUE THREAD

**Issue by spmacdonald** [lanl-ansi/PowerModelsAnnex.jl#45]
I find the `dc-opf` example to be a very useful self contained example of how the DC OPF algorithm can be implemented.

I would like to make a feature request for a similar example for a two stage scenario based security constrained DC OPF example.  My goal is to find the least cost dispatch such that if any predefined contingency occurs, the flows on the elements of the post contingency system are less than the emergency ratings.

I am keen to attempt to implement this but I am not sure where to start.  Can anyone suggest code samples or papers to read that might help?

Thanks

**Comment by ccoffrin** [comment]
In about 6 months time there will be a PowerModels extension package that is dedicated to SCOPF.  So I am inclined to delay this feature request until that time.

In the mean time, I recommend you have a look at this package, https://github.com/frederikgeth/PowerModelsReliability.jl

**Comment by spmacdonald** [comment]
Ok, good to know, thanks.

By PowerModels extension do you mean that development will occur outside of PowerModels repo?

**Comment by ccoffrin** [comment]
There will be a new package (e.g. PowerModelsSCOPF.jl) which will include
extensions to PowerModels forsolving that problem and several variants.

**Comment by ccoffrin** [comment]
I am closing this issue because it should be addressed by the new package [PowerModelsSecurityConstrained](https://github.com/lanl-ansi/PowerModelsSecurityConstrained.jl).  If there is a feature missing, feel free to post a specific issue in that repo.
