### ISSUE TITLE
Adding transformer tap and angle in frontend.

### ISSUE THREAD

**Issue by mjamei19** [lanl-ansi/PowerModelsAnnex.jl#56]
The transformer line data in the frontend does not parse the `tap` and `angle` of the transformers. Accordingly, the `network2pmc` function does map these two sets of data to a `pmc` format.

**Comment by ccoffrin** [comment]
FYI, @eperim

**Comment by eperim** [comment]
Sorry for the oversight. These elements were not present in any of the cases we had worked with, so they didn't show up in the frontend. @mjamei19 said he'll take care of adding that, though.
