### ISSUE TITLE
Remove Manifest.toml

### ISSUE THREAD

**Issue by nicoleepp** [lanl-ansi/PowerModelsAnnex.jl#57]
Just using the Project.toml should be good enough as the Manifest.toml is recreated locally for everyone from the Project.toml

**Comment by ccoffrin** [comment]
You are correct but there is a discussion in the Julia forums around what is the best convention for packages, to include an explicit Manifest.toml or not.  I am also a bit on the fence about it.  If you prefer not to have one for this package I am happy to remove it.

**Comment by nicoleepp** [comment]
I don't mind much just would be good to standardize among packages but if there is still discussion around it feel free to keep

**Comment by ccoffrin** [comment]
@nicoleepp I tried to remove the Manifest.tom file, but there seems to be an issue with the Julia package, but it is working on nightly.  So I am going to delay removing it until a later date.
