### ISSUE TITLE
Buildref in ac-opf.jl

### ISSUE THREAD

**Issue by fnbillimoria** [lanl-ansi/PowerModelsAnnex.jl#74]
Hello, I was attempting to run the code in ac-opf.jl and received an error when I run the following command:

ref = PowerModels.build_ref(pm_dict)[:nw][0]

The error I get is: ERROR: cannot assign a value to variable InfrastructureModels.ref from module Main

Not sure whether one of the variables is out of scope?    Any assistance would be greatly appreciated. 

Many thanks

**Comment by ccoffrin** [comment]
Is it possible you have an old version of PowerModels or InfrastructureModels?

I just gave this a try using PowerModelsAnnex#master version,
```
> include("ac-opf.jl")
```
and I got,
```
The solver termination status is LOCALLY_SOLVED
The cost of generation is 18269.10272278888.
The active power generated at generator 1 is 40.0 MW.
```

The packages installed in my system were,
```
(@v1.4) pkg> st
Status `~/.julia/environments/v1.4/Project.toml`
...
  [2030c09a] InfrastructureModels v0.5.3
  [b6b21f68] Ipopt v0.6.2
  [c36e90e8] PowerModels v0.17.2
```

**Comment by fnbillimoria** [comment]
Many thanks @ccoffrin - it seemed to work when i assigned ref with a new variable name... i.e. aref.
